language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

services: 
  - rabitmq
  - sqlite3

env:
  - DJANGO=2.1

before_install:
  - export DJANGO_SETTINGS_MODULE=flighty.settings
  - export PYTHONPATH=$HOME/builds/SEUNAGBEYE/Flighty

install:
  - pip install pipenv
  - pipenv install

script:
  - python manage.py collectstatic --noinput --settings=flighty.settings
  - sh ./build.sh