language: python
python:
  - "3.7.0"

services: 
  - rabitmq

env:
  - DJANGO=2.1.3
before_install:
  - export DJANGO_SETTINGS_MODULE=flighty.settings
install:
  - pip install pipenv
  - pipenv install

script:
  - sh ./build.sh
  - coveralls