# Generated by Django 2.1.5 on 2019-02-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('issuarance_country', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'passengers',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='number_of_travellers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_fare',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='form_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('None', 'Not paid')], max_length=100),
        ),
        migrations.AddField(
            model_name='passenger',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket'),
        ),
    ]
