# Generated by Django 2.1.5 on 2019-02-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190207_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='ticket.Ticket'),
        ),
    ]
