# Generated by Django 2.1.5 on 2019-02-08 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20190207_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='country',
        ),
    ]
